version: '3'

services:
  express:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    container_name: 'nodejs77'
    tty: true
    ports:
      - '3000:3000'
    volumes: 
      - './src:/usr/src'
    entrypoint: 'bash'
    working_dir: '/usr/src'

networks:
  default:
